---
# defaults file for JohnMcgrath.UbuntuMiner

#### See download notes in files/download notes before starting ####



miner_user_name: miner
miner_user_group: miner


base_file_dir: "{{ playbook_dir }}/roles/JohnMcgrath.UbuntuMiner/files"

amd_drivers: "amdgpu-pro-17.10-446706.tar.xz"

amd_app_sdk: "AMD-APP-SDK-v3.0.130.136-GA-linux64.sh"

amd_adl_sdk: "ADL_SDK"

#### All miner config files located in the temp folder ####

# use sgminer.conf
sg_miner_repo: "https://github.com/nicehash/sgminer.git"

sg_miner_username: password
sg_miner_password: password

#use config.text
claymore_package: Claymore's Dual Ethereum+Decred_Siacoin_Lbry_Pascal AMD+NVIDIA GPU Miner v9.7 - LINUX.tar.gz



