

- name: "FIX: Ubuntu 16.04 LTS doesn't come with certain modules, required by ansible"
  raw: apt-get install python-minimal aptitude -y
  become: true
  become_user: root
  become_method: sudo

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Update all packages to the latest version
  apt:
    upgrade: dist


- name: Install list of dependices
  apt: state=present name={{ item }}
  with_items:
   - libcurl4-openssl-dev
   - pkg-config
   - libtool
   - libncurses5-dev
   - htop
   - git
   - autoconf
   - ocl-icd-libopencl1
   - opencl-headers
   - clinfo
   - ocl-icd-opencl-dev
   - lm-sensors

- name: Copy AMD Graphic Drivers
  synchronize:
    src: "/{{ base_file_dir }}/{{ amd_drivers }}"
    dest: "/home/miner/."


#- name: Unpack Graphic Drivers
#  unarchive:
#      src: "/tmp/{{ amd_drivers }}"
#      dest: /tmp/.


- name: Copy AMD APP SDK
  synchronize:
    src: "/{{ base_file_dir }}/{{ amd_app_sdk }}"
    dest: "/home/miner/."


#- name: Install AMD APP SDK
#  expect:
#    command: /bin/bash -c "/tmp/{{ amd_app_sdk }}"
#    responses:
#      .* : " "
#      .* : " "
#      .* : " "
#      .* : " "
#      .*Do you accept the licence.* : "y"
#      .*choosing the default directory.* : "/opt"



- name: copy AMDADL GPU Monitor
  synchronize:
    src: "/{{ base_file_dir }}/{{ amd_adl_sdk }}/"
    dest: "/opt/AMDADL/"


- name: Change permission for miner in /opt
  file:
    dest: "/opt/."
    owner: "{{ miner_user_name }}"
    group: "{{ miner_user_group }}"
    recurse: yes
    mode: 0550


- name: create miner user
  user:
    name: "{{ miner_user_name }}"
    comment: "John Doe"
    uid: 1040
    group: "{{ miner_user_group }}"

- name: Add miner to video group
  user:
    name: "{{ miner_user_name }}"
    shell: /bin/bash
    groups: video
    append: yes

- name: Creates sgminer directory
  file:
    path: /home/miner/sgminer
    state: directory
    owner: "{{ miner_user_name }}"
    group: "{{ miner_user_group }}"
    mode: u+rw

- name: clone nice hash offical repo
  git:
    repo: "https://github.com/nicehash/sgminer.git"
    dest: /home/miner/sgminer
    update: no
    track_submodules: yes
    force: no


- name: copy AMD ADL header files
  raw: cp /opt/AMDADL/include/* /home/miner/sgminer/ADL_SDK/.



#- name: install sgminer
#git submodule init
#git submodule update
#autoreconf -i
# remove options to enable adl
#  CFLAGS="-O2 -Wall -march=native -std=gnu99" ./configure --disable-adl-checks --disable-adl
#make
#
- name: mining pool hub sgminer.conf
  template:
    src:  sgminer.conf
    dest: "/home/miner/sgminer/."
    owner: "{{ miner_user_name }}"
    group: "{{ miner_user_group }}"
    mode: u+rw



- name: Change permission for miner in /home/miner
  file:
    dest: "/home/miner/."
    owner: "{{ miner_user_name }}"
    group: "{{ miner_user_group }}"
    recurse: yes
    mode: 0770



# start config file sgminer -c sgminer.conf

#- name: Remove useless packages from the cache
#  apt:
#    autoclean: yes
#
#- name: Remove dependencies that are no longer required
#  apt:
#    autoremove: yes



