
- name: Creates sgminer directory
  file:
    path: /home/miner/sgminer
    state: directory
    owner: "{{ miner_user_name }}"
    group: "{{ miner_user_group }}"
    mode: u+rw

- name: clone sgminer repo
  git:
    repo: "{{ sg_miner_repo }}"
    dest: /home/miner/sgminer
    update: no
    track_submodules: yes
    force: no


- name: copy AMD ADL header files
  raw: cp /opt/AMDADL/include/* /home/miner/sgminer/ADL_SDK/.



#- name: install sgminer
# git submodule init
# git submodule update
# autoreconf -i
# remove options to enable adl ex. ./configure --disable-adl-checks --disable-adl
# CFLAGS="-O2 -Wall -march=native -std=gnu99" LDFLAGS="-L/opt/amdgpu-pro/lib/x86_64-linux-gnu" ./configure
# make or make install for global



- name: add sgminer json config
  template:
    src:  sgminer.conf
    dest: "/home/miner/sgminer/."
    owner: "{{ miner_user_name }}"
    group: "{{ miner_user_group }}"
    mode: u+rw




